#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  5 10:35:09 2021

@author: kaeashah
"""

from tkinter import*

root = Tk()

root.title("Drivers License ")
root.geometry("300x400")
root.configure(bg="white")
canvas = Canvas(root, width=300, height=400)
canvas.create_image(0, 0, anchor=NW)
canvas.create_rectangle(0, 0, 300, 55, fill="#1463B0")
canvas.create_rectangle(0, 345, 300, 400, fill="#1463B0")

label_heading = canvas.create_text(150, 90, font=('Times', '24', 'bold italic'), text="Identity Card")
label_name_tag = canvas.create_text(40, 165, font=('Times', '16', 'bold'), text="Name :")
label_grade_tag = canvas.create_text(40, 205, font=('Times', '16', 'bold'), text="Grade :")
label_subjects_tag = canvas.create_text(50, 250, font=('Times', '16', 'bold'), text="Subjects :")

label_name = Label(root)

label_grade = Label(root)

label_subjects = Label(root)

def myCardDetails():
    Id = "19827198349"
    print(type(name))
    name = "Winnie the Pooh"
    print(type(name))
    Date of Birth = "21 August 1921"
    print(type(Date of Birth))
    Pin No: = "451478"
    print(type(Pin No:))
    Address = "Disney Land , Hong Kong"
    print(type(Address))
    Authorisation to drive the following vehicles = "Two Four"
    print(type(Pin No:))
    
    label_Id['text'] = Id
    label_name['text'] = name
    label_Date of Birth['text'] = Date of Birth
    label_Pin No:['text'] = Pin No:
    label_Address['text'] = Address
    label_Authorisation to drive the following vehicles['text'] = name

button1 = Button(root,text = "Show my ID Card", command=myCardDetails)

button1.configure(width=20, activebackground="#9EC6EE", relief=FLAT)
button1_window = canvas.create_window(150, 330, anchor=CENTER, window=button1)
label_name_window = canvas.create_window(120, 165, anchor=CENTER, window=label_name)
label_grade_window = canvas.create_window(90, 205, anchor=CENTER, window=label_grade)
label_subjects_window = canvas.create_window(155, 252, anchor=CENTER, window=label_subjects)
canvas.pack()

root.mainloop()
